const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.gamepad,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.advert,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Share,
		C3.Plugins.Date,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Behaviors.destroy,
		C3.Behaviors.Flash,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform,
		C3.Behaviors.Timer,
		C3.Behaviors.custom,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.NinePatch,
		C3.Plugins.Particles,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.Pin,
		C3.Plugins.Dictionary,
		C3.Plugins.Multiplayer,
		C3.Behaviors.Bullet,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Spritefont2.Cnds.HasChildren,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Multiplayer.Acts.SyncObject2,
		C3.Plugins.Multiplayer.Acts.SyncObjectInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Multiplayer.Acts.SignallingConnect,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Browser.Exps.QueryParam,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Multiplayer.Cnds.OnSignallingConnected,
		C3.Plugins.Multiplayer.Acts.SignallingLogin,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Multiplayer.Cnds.OnSignallingLoggedIn,
		C3.Plugins.Multiplayer.Acts.SignallingAutoJoinRoom,
		C3.Plugins.Multiplayer.Acts.SignallingJoinRoom,
		C3.Plugins.Multiplayer.Cnds.OnSignallingJoinedRoom,
		C3.Plugins.Multiplayer.Cnds.IsHost,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Multiplayer.Cnds.OnPeerMessage,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Multiplayer.Acts.HostBroadcastMessage,
		C3.Plugins.Tilemap.Exps.AsJSON,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Exps.float,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Multiplayer.Exps.Message,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Multiplayer.Acts.SendPeerMessage,
		C3.Plugins.Tilemap.Acts.LoadFromJsonString,
		C3.Plugins.Multiplayer.Cnds.IsReadyForInput,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.advert.Cnds.OnInterstitialFailedToLoad,
		C3.Plugins.advert.Cnds.OnBannerFailedToLoad,
		C3.Plugins.advert.Cnds.OnBannerReady,
		C3.Plugins.advert.Acts.ShowBanner,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Particles.Exps.Timeout,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.gamepad.Cnds.OnButtonUp,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.NinePatch.Exps.LayerName,
		C3.Plugins.Multiplayer.Acts.SignallingDisconnect,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Tilemap.Exps.TileAt,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Tilemap.Exps.MapDisplayHeight,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Tilemap.Exps.TileWidth,
		C3.Plugins.Tilemap.Exps.MapDisplayWidth,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Tilemap.Acts.SetTileWithBrush,
		C3.Plugins.Tilemap.Exps.Height,
		C3.Plugins.Tilemap.Exps.PositionToTileX,
		C3.Plugins.Tilemap.Exps.PositionToTileY,
		C3.Plugins.Tilemap.Acts.EraseTile,
		C3.Plugins.Tilemap.Acts.EraseTileWithBrush,
		C3.Plugins.Tilemap.Cnds.CompareTileAt,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Tilemap.Exps.LayerName,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.Particles.Acts.SetSpeedRandomiser,
		C3.Plugins.Particles.Exps.InitSpeed,
		C3.Plugins.Particles.Acts.SetGravity,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.min,
		C3.Behaviors.custom.Acts.Stop,
		C3.Behaviors.custom.Acts.AcceleratePos,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.MeshColumns,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.MeshRows,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Sin.Exps.Value,
		C3.Behaviors.Sin.Exps.Magnitude,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.AdvancedRandom.Acts.CreateProbabilityTable,
		C3.Plugins.AdvancedRandom.Acts.AddProbabilityEntry,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.AdvancedRandom.Acts.SetProbabilityTable,
		C3.Plugins.AdvancedRandom.Exps.Weighted,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Acts.UpdateInitialState,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.LoadLayoutTextures,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.AJAX.Cnds.OnAnyComplete,
		C3.Plugins.AJAX.Cnds.OnAnyError,
		C3.Plugins.AJAX.Exps.Tag,
		C3.Plugins.AJAX.Exps.Progress,
		C3.Plugins.AJAX.Exps.LastStatusCode,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.Key,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnError,
		C3.Plugins.LocalStorage.Exps.ErrorMessage,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Exps.imageloadingprogress,
		C3.Plugins.Audio.Cnds.PreloadsComplete,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Spritefont2.Cnds.IsVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.JavaScriptInEvents.Common_Event50_Act2,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.JavaScriptInEvents.Common_Event54_Act2,
		C3.Plugins.Spritefont2.Exps.CharacterScale,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.log10,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.TiledBg.Exps.LayerName,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.advert.Cnds.IsConfigured,
		C3.Plugins.advert.Acts.CreateBanner,
		C3.Plugins.advert.Acts.CreateInterstitial,
		C3.Plugins.Share.Cnds.IsSupported,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Share.Acts.Share,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.advert.Acts.ShowInterstitial,
		C3.Plugins.Browser.Acts.Close,
		C3.Behaviors.Pin.Acts.PinByDistance,
		C3.Behaviors.Pin.Acts.SetPinDistance,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Sprite.Acts.SetPosToObject
	];
};
self.C3_JsPropNameTable = [
	{Gamepad: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{PlatformInfo: 0},
	{Touch: 0},
	{Browser: 0},
	{MobileAdvert: 0},
	{Audio: 0},
	{AJAX: 0},
	{LocalStorage: 0},
	{AdvancedRandom: 0},
	{Share: 0},
	{Date: 0},
	{PlayerId: 0},
	{Tween: 0},
	{Cannon: 0},
	{Solid: 0},
	{Terrain: 0},
	{Damage: 0},
	{Charge: 0},
	{mUID: 0},
	{Physics: 0},
	{DestroyOutsideLayout: 0},
	{Missile: 0},
	{Power: 0},
	{ExplosionCollider: 0},
	{Vertical: 0},
	{Tag: 0},
	{Margin: 0},
	{Flash: 0},
	{HP: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Sine: 0},
	{AIAimer: 0},
	{Avatar: 0},
	{CollectableSpawner: 0},
	{Destroy: 0},
	{ExplosionAnimation: 0},
	{Gem: 0},
	{Heart: 0},
	{AimAngle: 0},
	{Score: 0},
	{Charging: 0},
	{AI: 0},
	{mAngle: 0},
	{Platform: 0},
	{Timer: 0},
	{Player: 0},
	{PlayerSpawner: 0},
	{Tank: 0},
	{TankTracks: 0},
	{Distance: 0},
	{Range: 0},
	{BaseY: 0},
	{Custom: 0},
	{KeyboardInput: 0},
	{Loader: 0},
	{MeterCharge: 0},
	{Anchor: 0},
	{btStart: 0},
	{Logo: 0},
	{btAudio: 0},
	{btRestart: 0},
	{btClose: 0},
	{btPause: 0},
	{btResume: 0},
	{Banner: 0},
	{Center: 0},
	{Color: 0},
	{Crosshair: 0},
	{Window: 0},
	{Icon: 0},
	{btShare: 0},
	{MeterHP: 0},
	{MeterLoader: 0},
	{DirtVfx: 0},
	{DustVfx: 0},
	{Fire: 0},
	{FireVfx: 0},
	{Template: 0},
	{ReplacePrefix: 0},
	{HighScore: 0},
	{Label: 0},
	{Result: 0},
	{DigitCount: 0},
	{ResultScore: 0},
	{ResultTitle: 0},
	{Fade: 0},
	{Tutorial: 0},
	{Tutorial2: 0},
	{Pin: 0},
	{Result2: 0},
	{Speed: 0},
	{BGClouds: 0},
	{BGSky: 0},
	{BGSkyClouds: 0},
	{BGSkyMountains: 0},
	{btOSShoot: 0},
	{inX: 0},
	{inY: 0},
	{Angle_: 0},
	{PercentageX: 0},
	{PercentageY: 0},
	{VectorX: 0},
	{VectorY: 0},
	{DirectionX: 0},
	{DirectionY: 0},
	{DeltaX: 0},
	{DeltaY: 0},
	{DeadX: 0},
	{DeadY: 0},
	{Radius: 0},
	{OSMoveArea: 0},
	{OSMoveStick: 0},
	{OSAimArea: 0},
	{OSAimStick: 0},
	{OnscreenArrows: 0},
	{Config: 0},
	{TutorialBoard: 0},
	{Multiplayer: 0},
	{time: 0},
	{timeSystem: 0},
	{FMissile: 0},
	{FMeterContainer: 0},
	{FButton: 0},
	{FTextSF: 0},
	{FBG: 0},
	{SineOpacity: 0},
	{SineRotate: 0},
	{Bullet: 0},
	{FCollectable: 0},
	{FWindow: 0},
	{FMeter: 0},
	{FOSArea: 0},
	{DragDrop: 0},
	{FOSStick: 0},
	{GAME_NAME: 0},
	{INSTANCE_NAME: 0},
	{ROOM_NAME: 0},
	{MyUsername: 0},
	{playerIDPOSTID: 0},
	{GameFinished: 0},
	{CurrentPlayerId: 0},
	{done: 0},
	{avatar2: 0},
	{avatar1: 0},
	{tank2: 0},
	{tank1: 0},
	{TerrainUpdateTime: 0},
	{TileDestructable: 0},
	{TileIndestructible: 0},
	{tx: 0},
	{ty: 0},
	{pwidth: 0},
	{marginX: 0},
	{marginY: 0},
	{startX: 0},
	{startY: 0},
	{endX: 0},
	{endY: 0},
	{midX: 0},
	{left_: 0},
	{right_: 0},
	{y: 0},
	{x: 0},
	{power: 0},
	{delay: 0},
	{AllowOnscreenControls: 0},
	{AllowTouchControls: 0},
	{AllowKeyboardAim: 0},
	{lookAtX: 0},
	{lookAtY: 0},
	{originX: 0},
	{originY: 0},
	{radius: 0},
	{y_: 0},
	{x_: 0},
	{angle_: 0},
	{playerId: 0},
	{dir: 0},
	{charge: 0},
	{impulse: 0},
	{defender: 0},
	{iid1: 0},
	{iid2: 0},
	{playerId1: 0},
	{playerId2: 0},
	{cell_width: 0},
	{cell_height: 0},
	{TimerCooldown: 0},
	{range: 0},
	{pAngle: 0},
	{setAngle: 0},
	{sourceId: 0},
	{targetId: 0},
	{value: 0},
	{absoluteHP: 0},
	{avatar: 0},
	{tank: 0},
	{AIEnabled: 0},
	{enable: 0},
	{TableCollectables: 0},
	{total: 0},
	{object: 0},
	{setX: 0},
	{setY: 0},
	{setObject: 0},
	{client: 0},
	{setUID: 0},
	{width: 0},
	{i: 0},
	{mid_: 0},
	{max_probability: 0},
	{probability: 0},
	{mirror: 0},
	{vx: 0},
	{vy: 0},
	{Sep: 0},
	{FileNames: 0},
	{TotalFiles: 0},
	{LoadedFiles: 0},
	{name: 0},
	{StorageNames: 0},
	{TotalStorage: 0},
	{LoadedStorage: 0},
	{key: 0},
	{progress: 0},
	{caller: 0},
	{data: 0},
	{pause: 0},
	{state_group_name: 0},
	{change: 0},
	{s: 0},
	{m: 0},
	{TutorialSeen: 0},
	{animate: 0},
	{win: 0},
	{TagTweenValue: 0},
	{TagTweenSize: 0},
	{TagAudioCount: 0},
	{scale: 0},
	{number: 0},
	{hp: 0},
	{score: 0},
	{TagMusic: 0},
	{TagSfx: 0},
	{TagUI: 0},
	{loop: 0},
	{z: 0},
	{layer: 0},
	{count: 0},
	{text: 0},
	{textList: 0},
	{tag: 0},
	{h: 0},
	{w: 0},
	{InvertX: 0},
	{InvertY: 0},
	{pX_: 0},
	{threshold_: 0},
	{pY_: 0}
];

self.InstanceType = {
	Gamepad: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	MobileAdvert: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	AdvancedRandom: class extends self.IInstance {},
	Share: class extends self.IInstance {},
	Date: class extends self.IInstance {},
	Cannon: class extends self.ISpriteInstance {},
	Terrain: class extends self.ITilemapInstance {},
	Missile: class extends self.ISpriteInstance {},
	ExplosionCollider: class extends self.ISpriteInstance {},
	Charge: class extends self.ISpriteInstance {},
	HP: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	AIAimer: class extends self.ISpriteInstance {},
	Avatar: class extends self.ISpriteInstance {},
	CollectableSpawner: class extends self.ISpriteInstance {},
	Destroy: class extends self.ISpriteInstance {},
	ExplosionAnimation: class extends self.ISpriteInstance {},
	Gem: class extends self.ISpriteInstance {},
	Heart: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	PlayerSpawner: class extends self.ISpriteInstance {},
	Tank: class extends self.ISpriteInstance {},
	TankTracks: class extends self.ISpriteInstance {},
	KeyboardInput: class extends self.ISpriteInstance {},
	Loader: class extends self.ISpriteInstance {},
	MeterCharge: class extends self.ITiledBackgroundInstance {},
	btStart: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	btAudio: class extends self.ISpriteInstance {},
	btRestart: class extends self.ISpriteInstance {},
	btClose: class extends self.ISpriteInstance {},
	btPause: class extends self.ISpriteInstance {},
	btResume: class extends self.ISpriteInstance {},
	Banner: class extends self.ISpriteInstance {},
	Center: class extends self.ISpriteInstance {},
	Color: class extends self.ISpriteInstance {},
	Crosshair: class extends self.ISpriteInstance {},
	Window: class extends self.IWorldInstance {},
	Icon: class extends self.ISpriteInstance {},
	btShare: class extends self.ISpriteInstance {},
	MeterHP: class extends self.ITiledBackgroundInstance {},
	MeterLoader: class extends self.ITiledBackgroundInstance {},
	DirtVfx: class extends self.IParticlesInstance {},
	DustVfx: class extends self.IParticlesInstance {},
	Fire: class extends self.ISpriteInstance {},
	FireVfx: class extends self.IParticlesInstance {},
	HighScore: class extends self.ISpriteFontInstance {},
	Label: class extends self.ISpriteFontInstance {},
	Result: class extends self.ISpriteFontInstance {},
	ResultScore: class extends self.ISpriteFontInstance {},
	ResultTitle: class extends self.ISpriteFontInstance {},
	Score: class extends self.ISpriteFontInstance {},
	Timer: class extends self.ISpriteFontInstance {},
	Tutorial: class extends self.ISpriteFontInstance {},
	Tutorial2: class extends self.ISpriteFontInstance {},
	Result2: class extends self.ISpriteFontInstance {},
	BGClouds: class extends self.ITiledBackgroundInstance {},
	BGSky: class extends self.ITiledBackgroundInstance {},
	BGSkyClouds: class extends self.ITiledBackgroundInstance {},
	BGSkyMountains: class extends self.ITiledBackgroundInstance {},
	btOSShoot: class extends self.ISpriteInstance {},
	OSMoveArea: class extends self.ISpriteInstance {},
	OSMoveStick: class extends self.ISpriteInstance {},
	OSAimArea: class extends self.ISpriteInstance {},
	OSAimStick: class extends self.ISpriteInstance {},
	OnscreenArrows: class extends self.ISpriteInstance {},
	Config: class extends self.IDictionaryInstance {},
	TutorialBoard: class extends self.IWorldInstance {},
	Multiplayer: class extends self.IInstance {},
	timeSystem: class extends self.ISpriteInstance {},
	FMissile: class extends self.ISpriteInstance {},
	FMeterContainer: class extends self.ISpriteInstance {},
	FButton: class extends self.ISpriteInstance {},
	FTextSF: class extends self.ISpriteFontInstance {},
	FBG: class extends self.ITiledBackgroundInstance {},
	FCollectable: class extends self.ISpriteInstance {},
	FWindow: class extends self.IWorldInstance {},
	FMeter: class extends self.ITiledBackgroundInstance {},
	FOSArea: class extends self.ISpriteInstance {},
	FOSStick: class extends self.ISpriteInstance {}
}